import { readdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const MIGRATIONS_DIR = fileURLToPath(new URL("../migrations", import.meta.url));

/**
 * Load ordered migration SQL statements generated by `drizzle-kit generate`.
 * Statements are applied via {@link DbClient.migrate} so they run identically
 * on PGlite (dev/test) and Postgres (prod). Drizzle separates statements with a
 * `--> statement-breakpoint` marker.
 */
export async function loadMigrationStatements(throughFile?: string): Promise<string[]> {
  let files = (await readdir(MIGRATIONS_DIR))
    .filter((name) => name.endsWith(".sql"))
    .sort();
  if (throughFile !== undefined) {
    const last = files.indexOf(throughFile);
    if (last < 0) throw new Error("Unknown legacy migration boundary");
    files = files.slice(0, last + 1);
  }
  const statements: string[] = [];
  for (const file of files) {
    const contents = await readFile(`${MIGRATIONS_DIR}/${file}`, "utf8");
    for (const part of contents.split("--> statement-breakpoint")) {
      const trimmed = part.trim();
      if (trimmed.length > 0) {
        statements.push(trimmed);
      }
    }
  }
  return statements;
}
