import XCTest

/// One independent assistant suite. API calls observe outcomes or mint the
/// disposable pairing code; every conversation action uses the native UI.
final class AssistantConversationUITests: XCTestCase {
    private let app = XCUIApplication()
    private var fixture: AssistantFixture!

    override func setUpWithError() throws {
        continueAfterFailure = false
        fixture = try AssistantFixture(ProcessInfo.processInfo.environment)
    }
    override func tearDownWithError() throws { app.terminate() }

    @MainActor
    func testDirectAgentConversationAndRecovery() async throws {
        try await pair()
        try openChannel()
        try waitForLiveConnection()
        try demand(try await turns().isEmpty, "The assistant suite must begin without any precreated turn")
        try demand(try await messages().isEmpty, "The direct conversation must begin empty")
        try selectAgent()
        try await controlNode("stop")
        let firstMessageId = try await send(fixture.firstRequest)
        let firstWaiting = try await waitForTurn(fixture.firstRequest, status: "waiting")
        try demand(firstWaiting.userMessageId == firstMessageId, "The waiting turn must reference the exact native message that was visibly sent")
        try demand(firstWaiting.runId == nil && firstWaiting.responseMessageId == nil, "Offline waiting must not create a run or answer")
        let waitingTask: AssistantTaskEnvelope = try await get("api/v1/tasks/\(firstWaiting.taskId)")
        let waitingObservation = try await observations()
        try demand(waitingTask.runs.isEmpty && waitingObservation.receipts.isEmpty, "No subprocess may start while the selected computer is offline")
        try status(firstWaiting.id, "Waiting")

        let composer = field("messageComposer")
        try replace(composer, fixture.draft)
        try dismissKeyboard()
        app.terminate(); app.launch()
        try require(app.tabBars.buttons["Channels"].waitForExistence(timeout: 20), "Relaunch must restore the authenticated phone")
        try openChannel(); try waitForLiveConnection()
        try status(firstWaiting.id, "Waiting")
        try reveal(composer)
        try require(composer.value as? String == fixture.draft, "Relaunch must restore the unsent assistant draft exactly")
        try assertSelectedAgent()
        let restored = try await waitForTurn(fixture.firstRequest, status: "waiting")
        try demand(restored.id == firstWaiting.id && restored.userMessageId == firstWaiting.userMessageId && restored.runId == nil,
                   "Relaunch must preserve the same waiting logical request without resubmission")
        try revealTogether(composer, app.staticTexts["conversation.turn.status.\(firstWaiting.id)"], selectable: false)
        try screenshot("Native assistant waiting with draft restored")

        // Reconnection resumes waiting work automatically; no Retry is tapped.
        try await controlNode("start")
        let first = try await waitForTurn(fixture.firstRequest, status: "completed", timeout: 90)
        try demand(first.id == firstWaiting.id && first.userMessageId == firstWaiting.userMessageId, "Automatic dispatch must retain the original request")
        let firstRun = try await verifiedRun(first)
        try demand(firstRun.status == "completed", "The first process must complete")
        let firstAnswer = try await answer(first)
        try demand(firstAnswer.body.range(of: #"^First answer marker: ASSISTANT_[A-F0-9]{32}$"#, options: .regularExpression) != nil,
                   "The first answer must contain the marker generated by its real subprocess")
        try reveal(composer)
        try require(composer.value as? String == fixture.draft, "An arriving answer must not overwrite the unsent draft")
        try demand((try await observations()).receipts.count == 1, "Automatic recovery must launch exactly one process")

        let secondMessageId = try await send(fixture.secondRequest)
        let failed = try await waitForTurn(fixture.secondRequest, status: "failed", timeout: 90)
        try demand(failed.userMessageId == secondMessageId, "The failed follow-up must reference the exact native message that was visibly sent")
        let failedRun = try await verifiedRun(failed)
        try demand(failedRun.status == "failed" && failed.responseMessageId == nil, "The first follow-up attempt must actually fail without an answer")
        try status(failed.id, "Failed")
        let failedObservedMs = try await stable(failed, status: "failed", launches: 2, duration: 3.1)
        try reveal(app.buttons["conversation.turn.retry.\(failed.id)"])
        try require(!app.buttons["conversation.turn.cancel.\(failed.id)"].exists, "A failed request must offer Retry without a running Cancel action")
        try revealTogether(app.staticTexts["conversation.turn.request.\(failed.id)"], app.buttons["conversation.turn.retry.\(failed.id)"], selectable: false)
        try screenshot("Native assistant failed request before retry")
        let retry = app.buttons["conversation.turn.retry.\(failed.id)"]
        try require(retry.isEnabled && retry.isHittable, "Retry must be a reachable action for this specific failed request")
        retry.tap()
        let second = try await waitForTurn(fixture.secondRequest, status: "completed", timeout: 90, retryingRunId: failed.runId)
        try demand(second.id == failed.id && second.userMessageId == failed.userMessageId && second.runId != failed.runId,
                   "UI Retry must retain turn/message identity and create one distinct run")
        let secondRun = try await verifiedRun(second)
        try demand(secondRun.status == "completed", "The explicit retry must complete")
        let secondAnswer = try await answer(second)
        try demand(secondAnswer.body == "Follow-up used the actual earlier answer: \(firstAnswer.body)",
                   "The retry answer must use the first process's actual persisted answer")
        let firstText = app.staticTexts["message.\(firstAnswer.id)"], secondText = app.staticTexts["message.\(secondAnswer.id)"]
        // Real run events remain between the answers in this feed. Verify and
        // capture each complete answer without requiring both to fit one screen.
        try revealText(firstText)
        try require(firstText.label == firstAnswer.body, "The first answer must render its exact persisted content")
        try screenshot("Native assistant first completed answer")
        try revealText(secondText)
        try require(secondText.label == secondAnswer.body, "The follow-up answer must render its exact persisted content")
        try screenshot("Native assistant follow-up uses the actual first answer")

        let holdMessageId = try await send(fixture.holdRequest)
        let held = try await waitForTurn(fixture.holdRequest, status: "running", timeout: 90)
        try demand(held.userMessageId == holdMessageId, "The held turn must reference the exact native message that was visibly sent")
        let heldReceipt = try await waitForHeldProcess(held)
        let heldRun = try await verifiedRun(held)
        try demand(heldRun.status == "running", "The third turn must own a running process")
        try status(held.id, "Running")
        let taskLink = app.buttons["conversation.turn.task.\(held.id)"]
        try reveal(taskLink); taskLink.tap()
        let taskStatus = app.descendants(matching: .any).matching(identifier: "task.status.\(held.taskId)").firstMatch
        try require(taskStatus.waitForExistence(timeout: 15), "The request's linked execution task must open with its exact ID")
        try reveal(taskStatus)
        try require(taskStatus.value as? String == "running", "The linked task must reflect the actual running execution")
        let runLabel = "Run \(heldRun.id), Running"
        let runLinks = app.buttons.matching(NSPredicate(format: "label == %@", runLabel))
        let runLink = runLinks.firstMatch
        try reveal(runLink)
        try require(runLinks.firstMatch.waitForExistence(timeout: 15) && runLinks.count == 1,
                    "The linked task must offer exactly one running navigation row with this complete run ID")
        try require(runLink.label == runLabel && runLink.isHittable, "The exact running row must be visible before opening its summary")
        runLink.tap()
        try require(app.navigationBars["Run Summary"].waitForExistence(timeout: 15), "The actual held run must open its native summary")
        for value in [heldRun.id, held.taskId, fixture.instanceId, fixture.computerId] {
            let text = app.staticTexts.matching(NSPredicate(format: "label == %@", value)).firstMatch
            try revealText(text)
            try require(text.label == value, "Run Summary must expose exact task, run, computer and selected instance identities")
        }
        try screenshot("Native assistant linked execution task")
        app.navigationBars["Run Summary"].buttons.firstMatch.tap()
        try require(app.navigationBars["Task"].waitForExistence(timeout: 10), "Back must return to the linked task")
        app.navigationBars["Task"].buttons.firstMatch.tap()
        try demand((try await observations()).livePids.contains(heldReceipt.pid), "The held process must still be alive before UI cancellation")
        let cancel = app.buttons["conversation.turn.cancel.\(held.id)"]
        try reveal(cancel)
        try require(cancel.isEnabled && cancel.isHittable, "Cancel must target only the running request")
        cancel.tap()
        let cancelled = try await waitForTurn(fixture.holdRequest, status: "cancelled")
        try demand(cancelled.id == held.id && cancelled.runId == held.runId && cancelled.responseMessageId == nil,
                   "UI cancellation must terminate this same turn/run without creating an answer")
        let cancelledRun = try await verifiedRun(cancelled)
        try demand(cancelledRun.status == "cancelled", "The linked run must also be cancelled")
        try await waitForNoLiveProcesses()
        let cancelledObservedMs = try await stable(cancelled, status: "cancelled", launches: 4, duration: 3.1)
        try status(cancelled.id, "Cancelled")
        try require(!app.buttons["conversation.turn.cancel.\(held.id)"].exists && !app.buttons["conversation.turn.retry.\(held.id)"].exists,
                    "A cancelled request must not keep Retry or Cancel controls")
        try revealTogether(app.staticTexts["conversation.turn.request.\(held.id)"], app.staticTexts["conversation.turn.status.\(held.id)"], selectable: false)
        try screenshot("Native assistant cancelled with process stopped")

        let finalTurns = try await turns(), finalMessages = try await messages(), finalObservation = try await observations()
        try demand(finalTurns.count == 3 && finalObservation.receipts.count == 4 && finalObservation.livePids.isEmpty,
                   "The scenario must retain three turns, four launches and no live process")
        try demand(finalMessages.filter { $0.kind == "text" && $0.actorType == "agent" }.count == 2,
                   "Only the first request and successful follow-up may produce agent answers")
        try demand(!finalMessages.contains { $0.body == fixture.draft }, "The restored draft must never have been sent")
        let receipt = XCTAttachment(data: try JSONSerialization.data(withJSONObject: [
            "first_turn_id": first.id, "followup_turn_id": second.id, "cancelled_turn_id": held.id,
            "first_run_id": firstRun.id, "failed_run_id": failedRun.id, "retry_run_id": secondRun.id, "cancelled_run_id": heldRun.id,
            "held_pid": heldReceipt.pid, "failed_observed_ms": failedObservedMs, "cancelled_observed_ms": cancelledObservedMs,
            "restored_draft_remained_unsent": true, "runtime_scope": "deterministic CLI over production node WebSocket"
        ], options: .sortedKeys), uniformTypeIdentifier: "public.json")
        receipt.name = "Native assistant exact identities and observed lifecycle boundaries"; receipt.lifetime = .keepAlways; add(receipt)
    }

    @MainActor
    private func pair() async throws {
        app.launch()
        let readyOrigin = app.textFields.matching(identifier: "serverURL").matching(NSPredicate(format: "enabled == true")).firstMatch
        let deadline = Date().addingTimeInterval(30)
        while Date() < deadline && !app.tabBars.buttons["More"].exists && !readyOrigin.exists {
            try await Task.sleep(nanoseconds: 100_000_000)
        }
        if app.tabBars.buttons["More"].exists {
            app.tabBars.buttons["More"].tap()
            let signOut = app.buttons["signOut"]; try reveal(signOut); signOut.tap()
        }
        let serverField = readyOrigin
        try require(serverField.waitForExistence(timeout: 30), "Pairing must be available before entering the disposable credentials")
        let code: AssistantPairingCode = try await request(URLRequest(url: fixture.serverURL.appendingPathComponent("api/v1/devices/pairings")),
                                                          body: ["intended_platform": "ios"])
        if fixture.serverURL.scheme == "http" {
            let toggle = app.switches["allowLocalHTTP"]
            for _ in 0..<3 {
                try reveal(toggle)
                if toggle.value as? String == "1" { break }
                try require(toggle.value as? String == "0", "Local HTTP switch must expose a known state")
                let nested = toggle.switches.firstMatch; (nested.exists ? nested : toggle).tap()
                _ = XCTWaiter.wait(for: [XCTNSPredicateExpectation(predicate: NSPredicate(format: "value == %@", "1"), object: toggle)], timeout: 3)
            }
            try require(toggle.value as? String == "1", "Loopback HTTP must be enabled through the real onboarding switch")
        }
        try replace(serverField, fixture.serverURL.absoluteString)
        try replace(app.textFields["pairingDeviceName"], fixture.deviceName)
        try replace(app.textFields["pairingCode"], code.code)
        let pair = app.buttons["pairDevice"]; try reveal(pair); try require(pair.isEnabled, "The completed pairing form must allow connection"); pair.tap()
        try require(app.tabBars.buttons["Channels"].waitForExistence(timeout: 20), "Native UI pairing must authenticate and load the shared server")
    }

    @MainActor
    private func openChannel() throws {
        app.tabBars.buttons["Channels"].tap()
        try require(app.navigationBars["Channels"].waitForExistence(timeout: 15), "Channels must show the real channel inventory")
        let channel = app.buttons["channel.\(fixture.channelId)"]; try require(channel.waitForExistence(timeout: 15), "The empty assistant channel must exist")
        try reveal(channel); channel.tap()
    }

    @MainActor
    private func selectAgent() throws {
        let destination = app.descendants(matching: .any).matching(identifier: "conversation.destination").firstMatch
        try reveal(destination); destination.tap()
        let agent = app.buttons["Agent"]; try require(agent.waitForExistence(timeout: 5), "The destination picker must offer Agent"); agent.tap()
        let picker = app.descendants(matching: .any).matching(identifier: "conversation.agent").firstMatch
        try reveal(picker); picker.tap()
        let selected = try agentOption(fixture.instanceId), collision = try agentOption(fixture.collisionId)
        for (option, id, other) in [(selected, fixture.instanceId, fixture.collisionId), (collision, fixture.collisionId, fixture.instanceId)] {
            try require(option.label.contains(fixture.agentName) && option.label.contains(fixture.computerName)
                        && option.label.contains(fixture.runtime) && option.label.contains("Instance: \(id)") && !option.label.contains(other),
                        "Same-name agent choices must retain readable details and their complete distinct instance IDs")
        }
        try revealTogether(selected, collision, selectable: false)
        try screenshot("Native assistant readable agent selection")
        selected.tap()
        try assertSelectedAgent()
    }

    @MainActor
    private func agentOption(_ id: String) throws -> XCUIElement {
        let found = app.descendants(matching: .any).matching(identifier: "conversation.agent.option.\(id)").firstMatch
        if found.waitForExistence(timeout: 2) { return found }
        let exactIdentity = app.buttons.matching(NSPredicate(format: "label CONTAINS %@", "Instance: \(id)"))
        try require(exactIdentity.firstMatch.waitForExistence(timeout: 5) && exactIdentity.count == 1, "Agent option fallback must identify one complete instance ID")
        return exactIdentity.firstMatch
    }

    @MainActor
    private func assertSelectedAgent() throws {
        let picker = app.descendants(matching: .any).matching(identifier: "conversation.agent").firstMatch
        try reveal(picker)
        let value = picker.value as? String ?? picker.label
        try require(value.contains(fixture.agentName) && value.contains(fixture.computerName) && value.contains(fixture.runtime)
                    && value.contains("Instance: \(fixture.instanceId)") && !value.contains(fixture.collisionId),
                    "The composer must retain the original chosen instance, including after relaunch")
    }

    @MainActor
    private func send(_ text: String) async throws -> String {
        try replace(field("messageComposer"), text); try dismissKeyboard()
        let send = app.buttons["sendMessage"]; try reveal(send)
        try require(send.isEnabled && send.label == "Send to agent", "The real composer must send an agent request")
        send.tap()
        let deadline = Date().addingTimeInterval(15)
        var persisted: AssistantMessage?
        repeat {
            let matching = try await messages().filter {
                $0.kind == "text" && $0.actorType == "user" && $0.actorId == fixture.userId && $0.body == text
            }
            try require(matching.count <= 1, "The current recipient's native send must persist exactly once")
            if let message = matching.first {
                try require(message.threadRootId == nil, "The sent message must belong to this top-level conversation")
                persisted = message; break
            }
            try await Task.sleep(nanoseconds: 250_000_000)
        } while Date() < deadline
        try require(persisted != nil, "The native send must produce its real recipient-authored message")
        let message = try XCTUnwrap(persisted)
        // The request card repeats the body. A label-first query can change
        // targets as SwiftUI materializes rows; the persisted message ID cannot.
        let sent = app.staticTexts["message.\(message.id)"]
        try revealText(sent)
        try require(sent.waitForExistence(timeout: 15) && sent.label == text, "The native request must visibly retain its exact submitted text")
        return message.id
    }

    @MainActor
    private func status(_ id: String, _ expected: String) throws {
        let label = app.staticTexts["conversation.turn.status.\(id)"]
        // SwiftUI List materializes this section only after it is scrolled into
        // view; waiting for existence at the composer can never reveal it.
        try reveal(label)
        try require(label.waitForExistence(timeout: 20), "The specific assistant request must have a native status row")
        let updated = XCTNSPredicateExpectation(predicate: NSPredicate(format: "label == %@", expected), object: label)
        try require(XCTWaiter.wait(for: [updated], timeout: 20) == .completed, "The native request must display \(expected)")
        try reveal(label)
        try require(label.label == expected && label.isHittable, "The exact request status must remain visibly \(expected)")
    }

    @MainActor
    private func field(_ id: String) -> XCUIElement {
        // Keep the exact query valid while an offscreen input is not materialized;
        // choosing its native element type from exists would lock in a wrong query.
        app.descendants(matching: .any).matching(identifier: id).firstMatch
    }
    @MainActor
    private func replace(_ field: XCUIElement, _ text: String) throws {
        try reveal(field)
        try require(field.waitForExistence(timeout: 15) && field.isHittable, "The required exact input must be visible"); field.tap()
        if let value = field.value as? String, !value.isEmpty && value != field.placeholderValue { field.typeText(String(repeating: XCUIKeyboardKey.delete.rawValue, count: value.count)) }
        field.typeText(text)
    }
    @MainActor
    private func dismissKeyboard() throws {
        let done = app.buttons["conversation.keyboard.done"]
        try require(done.waitForExistence(timeout: 10) && done.isHittable, "The native multiline composer must expose Done"); done.tap()
        try require(XCTWaiter.wait(for: [XCTNSPredicateExpectation(predicate: NSPredicate(format: "exists == false"), object: app.keyboards.firstMatch)], timeout: 10) == .completed,
                    "Done must dismiss the keyboard before conversation actions")
    }
    @MainActor
    private func waitForLiveConnection() throws {
        let connected = app.descendants(matching: .any).matching(identifier: "realtimeStatus").matching(NSPredicate(format: "value == %@", "connected")).firstMatch
        try require(connected.waitForExistence(timeout: 20), "The phone must connect its authenticated WebSocket")
    }
    @MainActor
    private func reveal(_ element: XCUIElement) throws {
        for _ in 0..<7 { if element.exists && element.isHittable { return }; app.swipeUp() }
        for _ in 0..<7 { if element.exists && element.isHittable { return }; app.swipeDown() }
        try require(element.exists && element.isHittable, "The requested native control must be reachable")
    }
    @MainActor
    private func viewport() throws -> CGRect {
        let list = app.collectionViews.firstMatch
        try require(list.exists && !app.keyboards.firstMatch.exists, "Evidence must use an unobscured native list")
        let rect = list.frame.intersection(app.frame), nav = app.navigationBars.firstMatch, tabs = app.tabBars.firstMatch
        let top = nav.exists ? max(rect.minY, nav.frame.maxY) : rect.minY
        let bottom = tabs.exists ? min(rect.maxY, tabs.frame.minY) : rect.maxY
        let visible = CGRect(x: rect.minX + 2, y: top + 2, width: rect.width - 4, height: bottom - top - 4)
        try require(!visible.isEmpty && !visible.isNull && !visible.isInfinite, "The content viewport must have a real visible frame")
        return visible
    }
    @MainActor
    private func drag(_ view: CGRect, upward: Bool) {
        let origin = app.coordinate(withNormalizedOffset: .zero)
        origin.withOffset(CGVector(dx: view.midX, dy: view.minY + view.height * (upward ? 0.7 : 0.3)))
            .press(forDuration: 0.05, thenDragTo: origin.withOffset(CGVector(dx: view.midX, dy: view.minY + view.height * (upward ? 0.3 : 0.7))))
    }
    @MainActor
    private func revealText(_ element: XCUIElement) throws {
        for attempt in 0..<24 {
            let view = try viewport(); var upward = attempt < 12
            if element.exists {
                let rect = element.frame
                if !rect.isEmpty && !rect.isNull && !rect.isInfinite {
                    let visible = rect.intersection(view)
                    let requiredHeight = rect.height <= view.height ? rect.height : view.height / 2
                    if !visible.isNull && visible.width >= rect.width - 1 && visible.height >= requiredHeight - 1 { return }
                    upward = rect.midY > view.midY
                }
            }
            drag(view, upward: upward)
        }
        try require(false, "The exact read-only text must be visibly rendered")
    }
    @MainActor
    private func revealTogether(_ first: XCUIElement, _ second: XCUIElement, selectable: Bool) throws {
        for attempt in 0..<18 {
            let view = try viewport(); var upward = attempt < 9
            if first.exists && second.exists {
                let frames = [first.frame, second.frame]
                if frames.allSatisfy({ !$0.isEmpty && !$0.isNull && !$0.isInfinite }) {
                    if frames.allSatisfy({ view.contains($0) }) && (selectable || (first.isHittable && second.isHittable)) { return }
                    upward = frames[0].union(frames[1]).midY > view.midY
                }
            }
            drag(view, upward: upward)
        }
        try require(false, "Both pieces of visual evidence must be visible together")
    }
    @MainActor
    private func screenshot(_ name: String) throws {
        for id in ["serverURL", "pairingDeviceName", "pairingCode", "device.pairing.code"] {
            try require(!app.descendants(matching: .any).matching(identifier: id).firstMatch.exists, "Approved screenshots must exclude pairing fields and generated codes")
        }
        let image = XCTAttachment(screenshot: app.screenshot()); image.name = name; image.lifetime = .keepAlways; add(image)
    }
    @MainActor
    private func require(_ condition: Bool, _ message: String) throws {
        if !condition {
            let credentialsVisible = ["serverURL", "pairingDeviceName", "pairingCode", "device.pairing.code"].contains {
                app.descendants(matching: .any).matching(identifier: $0).firstMatch.exists
            }
            if !credentialsVisible {
                let image = XCTAttachment(screenshot: app.screenshot()); image.name = "Native assistant guarded failure diagnostics"; image.lifetime = .keepAlways; add(image)
                let tree = XCTAttachment(string: app.debugDescription); tree.name = "Native assistant failure accessibility hierarchy"; tree.lifetime = .keepAlways; add(tree)
            }
        }
        try demand(condition, message)
    }

    private func turns() async throws -> [AssistantTurnRecord] { let page: AssistantTurnPage = try await get("api/v1/rooms/\(fixture.channelId)/assistant-turns"); return page.turns }
    private func messages() async throws -> [AssistantMessage] { let page: AssistantMessagePage = try await get("api/v1/rooms/\(fixture.channelId)/messages?limit=100"); return page.messages }
    private func waitForTurn(_ body: String, status: String, timeout: TimeInterval = 30, retryingRunId: String? = nil) async throws -> AssistantTurnRecord {
        let deadline = Date().addingTimeInterval(timeout)
        repeat {
            let matching = try await messages().filter { $0.kind == "text" && $0.body == body }
            try demand(matching.count <= 1, "A native request must persist exactly once")
            if let request = matching.first {
                try demand(request.actorType == "user" && request.actorId == fixture.userId && request.threadRootId == nil,
                           "The request must belong to the actual native user in this top-level conversation")
                let candidates = try await turns().filter { $0.userMessageId == request.id }
                try demand(candidates.count <= 1, "A native message must create only one logical turn")
                if let turn = candidates.first {
                    try demand(request.payload?.assistantTurnId == turn.id && turn.roomId == fixture.channelId && turn.threadRootId == nil,
                               "The request and actual turn must retain the same conversation identities")
                    if turn.status == status { return turn }
                    let awaitingRetry = status == "completed" && turn.status == "failed" && retryingRunId != nil && turn.runId == retryingRunId
                    if ["failed", "cancelled"].contains(turn.status) && turn.status != status && !awaitingRetry { throw assistantError("Assistant turn ended unexpectedly as \(turn.status)") }
                }
            }
            try await Task.sleep(nanoseconds: 250_000_000)
        } while Date() < deadline
        throw assistantError("The actual assistant turn did not reach \(status)")
    }
    private func verifiedRun(_ turn: AssistantTurnRecord) async throws -> AssistantRun {
        let id = try XCTUnwrap(turn.runId), envelope: AssistantRunEnvelope = try await get("api/v1/runs/\(id)")
        let run = envelope.run
        try demand(run.id == id && run.taskId == turn.taskId && run.computerId == fixture.computerId
                   && run.agentInstanceId == fixture.instanceId && run.runtimeId == fixture.runtime,
                   "The run must use the exact manually selected original agent, computer and runtime")
        return run
    }
    private func answer(_ turn: AssistantTurnRecord) async throws -> AssistantMessage {
        let id = try XCTUnwrap(turn.responseMessageId), rows = try await messages().filter { $0.id == id }
        try demand(rows.count == 1, "A completed turn must have exactly one persisted answer")
        let answer = rows[0]
        try demand(answer.actorType == "agent" && answer.actorId == fixture.instanceId && answer.threadRootId == nil && answer.payload?.assistantTurnId == turn.id,
                   "The answer must be attributed to the selected instance and exact turn")
        return answer
    }
    private func observations() async throws -> AssistantObservations {
        let deadline = Date().addingTimeInterval(20)
        repeat {
            let snapshot: AssistantObservations = try await request(URLRequest(url: fixture.controlURL.appendingPathComponent("observations")), token: fixture.controlToken)
            if snapshot.incompleteReceipts.isEmpty { return snapshot }
            try await Task.sleep(nanoseconds: 150_000_000)
        } while Date() < deadline
        throw assistantError("An owned startup receipt did not finish writing within the observation deadline")
    }
    private func controlNode(_ action: String) async throws {
        try demand(["start", "stop"].contains(action), "Fixture control only starts or stops the real node")
        let value: AssistantNodeResponse = try await request(URLRequest(url: fixture.controlURL.appendingPathComponent("node/\(action)")),
                                                            token: fixture.controlToken, body: [:], timeout: 75)
        try demand(value.daemon.computerId == fixture.computerId && value.daemon.status == (action == "start" ? "online" : "offline")
                   && value.daemon.connected == (action == "start"), "Node control must observe actual authenticated presence")
    }
    private func waitForHeldProcess(_ turn: AssistantTurnRecord) async throws -> AssistantProcessReceipt {
        let deadline = Date().addingTimeInterval(20)
        repeat {
            let snapshot = try await observations(), matches = snapshot.receipts.filter { $0.runId == turn.runId && $0.turnId == turn.id }
            try demand(matches.count <= 1, "The held run must have only one startup receipt")
            if let receipt = matches.first, snapshot.livePids.contains(receipt.pid) {
                try demand(receipt.mode == "hold" && receipt.taskId == turn.taskId && receipt.pid > 1 && snapshot.receipts.count == 4,
                           "The fourth launch must be the actual held process")
                return receipt
            }
            try await Task.sleep(nanoseconds: 150_000_000)
        } while Date() < deadline
        throw assistantError("The real held subprocess was never observed alive")
    }
    private func waitForNoLiveProcesses() async throws {
        let deadline = Date().addingTimeInterval(30)
        repeat {
            if try await observations().livePids.isEmpty { return }
            try await Task.sleep(nanoseconds: 150_000_000)
        } while Date() < deadline
        throw assistantError("UI cancellation did not terminate the held subprocess")
    }
    private func stable(_ expected: AssistantTurnRecord, status: String, launches: Int, duration: TimeInterval) async throws -> Int {
        let start = Date()
        repeat {
            let current = try await turns().filter { $0.id == expected.id }
            try demand(current.count == 1 && current[0].status == status && current[0].runId == expected.runId
                       && current[0].userMessageId == expected.userMessageId && current[0].responseMessageId == nil,
                       "The terminal request must keep its same identities until the explicit next action")
            let observed = try await observations()
            try demand(observed.receipts.count == launches && observed.livePids.isEmpty, "A terminal turn must not dispatch or leave a process running")
            try await Task.sleep(nanoseconds: 250_000_000)
        } while Date().timeIntervalSince(start) < duration
        return Int(Date().timeIntervalSince(start) * 1000)
    }
    private func get<T: Decodable>(_ path: String) async throws -> T {
        try await request(URLRequest(url: try XCTUnwrap(URL(string: path, relativeTo: fixture.serverURL.appendingPathComponent("/"))).absoluteURL))
    }
    private func request<T: Decodable>(_ initial: URLRequest, token: String? = nil, body: [String: String]? = nil, timeout: TimeInterval = 20) async throws -> T {
        var request = initial; request.timeoutInterval = timeout
        request.setValue("Bearer \(token ?? fixture.peerToken)", forHTTPHeaderField: "Authorization")
        if let body {
            request.httpMethod = "POST"; request.setValue("application/json", forHTTPHeaderField: "Content-Type")
            request.setValue(UUID().uuidString, forHTTPHeaderField: "Idempotency-Key"); request.httpBody = try JSONSerialization.data(withJSONObject: body)
        }
        let config = URLSessionConfiguration.ephemeral; config.httpShouldSetCookies = false
        let session = URLSession(configuration: config); defer { session.invalidateAndCancel() }
        let (data, response) = try await session.data(for: request), http = try XCTUnwrap(response as? HTTPURLResponse)
        try demand((200..<300).contains(http.statusCode), "Authenticated assistant observation failed with HTTP \(http.statusCode)")
        let decoder = JSONDecoder(); decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(T.self, from: data)
    }
}

private func assistantError(_ message: String) -> NSError { NSError(domain: "ArtooAssistantUITest", code: 1, userInfo: [NSLocalizedDescriptionKey: message]) }
private func demand(_ condition: Bool, _ message: String) throws { if !condition { throw assistantError(message) } }
private struct AssistantPairingCode: Decodable { let code: String }
private struct AssistantTurnPage: Decodable { let turns: [AssistantTurnRecord] }
private struct AssistantTurnRecord: Decodable { let id: String; let roomId: String; let threadRootId: String?; let taskId: String; let runId: String?; let userMessageId: String; let responseMessageId: String?; let status: String }
private struct AssistantMessagePage: Decodable { let messages: [AssistantMessage] }
private struct AssistantMessage: Decodable { let id: String; let kind: String; let body: String; let actorType: String; let actorId: String; let threadRootId: String?; let payload: AssistantMessagePayload? }
private struct AssistantMessagePayload: Decodable { let assistantTurnId: String? }
private struct AssistantTaskEnvelope: Decodable { let runs: [AssistantRun] }
private struct AssistantRunEnvelope: Decodable { let run: AssistantRun }
private struct AssistantRun: Decodable { let id: String; let taskId: String; let status: String; let runtimeId: String; let agentInstanceId: String; let computerId: String }
private struct AssistantNodeResponse: Decodable { let daemon: AssistantDaemon }
private struct AssistantDaemon: Decodable { let computerId: String; let status: String; let connected: Bool }
private struct AssistantObservations: Decodable { let receipts: [AssistantProcessReceipt]; let livePids: [Int]; let incompleteReceipts: [String] }
private struct AssistantProcessReceipt: Decodable { let pid: Int; let runId: String; let turnId: String; let taskId: String; let mode: String }
private struct AssistantFixture {
    let serverURL: URL; let controlURL: URL; let peerToken: String; let controlToken: String
    let channelId: String; let userId: String; let deviceName: String; let instanceId: String; let collisionId: String
    let agentName: String; let runtime: String; let computerId: String; let computerName: String
    let firstRequest: String; let secondRequest: String; let holdRequest: String; let draft: String
    init(_ environment: [String: String]) throws {
        func read(_ key: String) throws -> String {
            guard let value = environment["ARTOO_UI_\(key)"], !value.isEmpty else { throw assistantError("Missing native assistant fixture field \(key)") }
            return value
        }
        serverURL = try XCTUnwrap(URL(string: read("SERVER_URL"))); controlURL = try XCTUnwrap(URL(string: read("FIXTURE_CONTROL_URL")))
        peerToken = try read("PEER_CONTROL_TOKEN"); controlToken = try read("FIXTURE_CONTROL_TOKEN")
        channelId = try read("CHANNEL_ID"); userId = try read("USER_ID"); deviceName = try read("ASSISTANT_DEVICE_NAME")
        instanceId = try read("ASSISTANT_INSTANCE_ID"); collisionId = try read("ASSISTANT_COLLISION_INSTANCE_ID")
        agentName = try read("ASSISTANT_NAME"); runtime = try read("ASSISTANT_RUNTIME")
        computerId = try read("COMPUTER_ID"); computerName = try read("COMPUTER_NAME")
        firstRequest = try read("ASSISTANT_FIRST_REQUEST"); secondRequest = try read("ASSISTANT_SECOND_REQUEST")
        holdRequest = try read("ASSISTANT_HOLD_REQUEST"); draft = try read("ASSISTANT_DRAFT")
    }
}
