import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { getE2EReportContext } from "./e2e-report.mjs";

test("source fingerprint excludes generated trees before collection while detecting untracked source edits", () => {
  const root = mkdtempSync(join(tmpdir(), "artoo-source-context-"));
  try {
    const git = (...args) => execFileSync("git", args, { cwd: root, stdio: "ignore" });
    git("init"); git("config", "user.email", "fixture@example.test"); git("config", "user.name", "Fixture");
    writeFileSync(join(root, "tracked.ts"), "export const tracked = true;\n"); git("add", "tracked.ts"); git("commit", "-m", "fixture");
    for (const path of ["artifacts", "apps/client/artifacts", "apps/client/dist", "apps/ios/Artoo.xcodeproj"]) {
      mkdirSync(join(root, path), { recursive: true }); writeFileSync(join(root, path, "generated.swift"), "generated bytes");
    }
    mkdirSync(join(root, "apps/client/src"), { recursive: true });
    const source = join(root, "apps/client/src/new.ts"); writeFileSync(source, "first");
    const first = getE2EReportContext(root).source;
    assert.equal(first.untracked_source_complete, true); assert.equal(first.untracked_source_files, 1);
    writeFileSync(join(root, "artifacts/generated.swift"), "different generated bytes");
    assert.equal(getE2EReportContext(root).source.untracked_source_sha256, first.untracked_source_sha256);
    writeFileSync(source, "second"); assert.notEqual(getE2EReportContext(root).source.untracked_source_sha256, first.untracked_source_sha256);
  } finally { rmSync(root, { recursive: true, force: true }); }
});
